#!/usr/bin/env bash
# ============================================================
# generate-delete.sh
# Generates cloudshell/<org>/delete.sh — a full teardown script
# for testing / emergency rollback. NOT for routine use.
# ============================================================
set -euo pipefail

TFVARS_FILE="${TFVARS_FILE:-}"

[[ -z "$TFVARS_FILE" ]]   && echo "[ERROR] TFVARS_FILE not set"            && exit 1
[[ ! -f "$TFVARS_FILE" ]] && echo "[ERROR] tfvars not found: $TFVARS_FILE" && exit 1

# ── Parse tfvars ────────────────────────────────────────────

get_var() {
  local key="$1"
  grep -E "^${key}[[:space:]]*=" "$TFVARS_FILE" | head -n1 \
    | sed -E 's/.*=[[:space:]]*"?([^"#]+)"?.*/\1/' | xargs
}

# Parse multi-line OU ID list into space-separated string
OU_IDS=$(python3 - <<PYEOF
import re
content = open("${TFVARS_FILE}").read()
match = re.search(r'target_organizational_unit_ids\s*=\s*\[(.*?)\]', content, re.DOTALL)
if match:
    ids = re.findall(r'"([^"]+)"', match.group(1))
    print(" ".join(ids))
PYEOF
)

ORG="$(get_var org)"
ENVIRONMENT="$(get_var environment)"
PARTITION="$(get_var partition)"
AWS_REGION="$(get_var aws_region)"
SYSTEM="$(get_var system)"

case "$PARTITION" in
  aws)        partition_short="cmc"  ;;
  aws-us-gov) partition_short="gvc"  ;;
  *) echo "[ERROR] Invalid partition: $PARTITION"; exit 1 ;;
esac

case "$AWS_REGION" in
  us-east-1)     region_short="use1"   ;;
  us-west-1)     region_short="usw1"   ;;
  us-west-2)     region_short="usw2"   ;;
  eu-west-1)     region_short="euw1"   ;;
  us-gov-west-1) region_short="usgw1"  ;;
  us-gov-east-1) region_short="usge1"  ;;
  *) echo "[ERROR] Invalid region: $AWS_REGION"; exit 1 ;;
esac

NAME_PREFIX="${ORG}-${partition_short}-${region_short}-${SYSTEM}"
ROLE_NAME="${NAME_PREFIX}-oidc-role"
POLICY_NAME="${NAME_PREFIX}-assume-member-roles"
TF_STATE_BUCKET="${NAME_PREFIX}-tfstate-${ENVIRONMENT}"
TF_LOGS_BUCKET="${NAME_PREFIX}-logs-${ENVIRONMENT}"
KMS_ALIAS="alias/${NAME_PREFIX}-tfstate"
STACKSET_NAME="${NAME_PREFIX}-member-role"

TFVARS_BASENAME="$(basename "$TFVARS_FILE" .tfvars)"
OUTPUT_FILE="cloudshell/${TFVARS_BASENAME}/delete.sh"

mkdir -p "cloudshell/${TFVARS_BASENAME}"

cat > "$OUTPUT_FILE" <<EOF
#!/usr/bin/env bash
# ============================================================
# DELETE SCRIPT — ${TFVARS_BASENAME}
# ⚠️  DESTRUCTIVE: Removes ALL seed resources for this tenant.
#    For testing / emergency rollback ONLY. Not for routine use.
#    Generated by: tools/generate-delete.sh
# ============================================================
set -euo pipefail

AWS_REGION="${AWS_REGION}"
PARTITION="${PARTITION}"
ROLE_NAME="${ROLE_NAME}"
POLICY_NAME="${POLICY_NAME}"
TF_STATE_BUCKET="${TF_STATE_BUCKET}"
TF_LOGS_BUCKET="${TF_LOGS_BUCKET}"
KMS_ALIAS="${KMS_ALIAS}"
STACKSET_NAME="${STACKSET_NAME}"
OU_IDS=(${OU_IDS})

ACCOUNT_ID=\$(aws sts get-caller-identity --query Account --output text)

########################################
# SAFETY CONFIRMATION
########################################

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║  ⚠️   DESTRUCTIVE OPERATION — READ CAREFULLY          ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  This will permanently delete:                       ║"
echo "║    • CloudFormation StackSet + all member instances  ║"
echo "║    • IAM role + all policies: \${ROLE_NAME}           ║"
echo "║    • IAM policy: \${POLICY_NAME}                      ║"
echo "║    • S3 bucket (all versions): \${TF_STATE_BUCKET}    ║"
echo "║    • S3 bucket (all versions): \${TF_LOGS_BUCKET}     ║"
echo "║    • KMS key alias + schedule deletion               ║"
echo "║    • GitHub Actions OIDC provider                    ║"
echo "║                                                      ║"
echo "║  Account : \${ACCOUNT_ID}                             ║"
echo "║  Region  : ${AWS_REGION}                             ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
read -r -p "  Type the org name to confirm [${TFVARS_BASENAME}]: " CONFIRM
if [[ "\${CONFIRM}" != "${TFVARS_BASENAME}" ]]; then
  echo "[ABORT] Confirmation did not match. Nothing deleted."
  exit 1
fi
echo ""

########################################
# HELPER: empty a versioned S3 bucket
# Handles: versioned objects, delete markers, plain objects
########################################

empty_versioned_bucket() {
  local bucket="\$1"
  local tmpfile

  echo "[INFO] Emptying versioned bucket: \${bucket}"

  # Delete all object versions in batches
  while true; do
    local batch
    batch=\$(aws s3api list-object-versions \
      --bucket "\${bucket}" \
      --max-items 1000 \
      --query 'Versions[].{Key:Key,VersionId:VersionId}' \
      --output json 2>/dev/null || echo "null")
    [[ "\${batch}" == "null" || "\${batch}" == "[]" || -z "\${batch}" ]] && break

    tmpfile=\$(mktemp)
    printf '%s' "\${batch}" | python3 -c "
import json, sys
objs = json.load(sys.stdin)
if objs: print(json.dumps({'Objects': objs}))
" > "\${tmpfile}"
    [[ -s "\${tmpfile}" ]] && \
      aws s3api delete-objects --bucket "\${bucket}" --delete "file://\${tmpfile}" >/dev/null && \
      echo "[INFO]   Deleted version batch"
    rm -f "\${tmpfile}"
  done

  # Delete all delete markers in batches
  while true; do
    local batch
    batch=\$(aws s3api list-object-versions \
      --bucket "\${bucket}" \
      --max-items 1000 \
      --query 'DeleteMarkers[].{Key:Key,VersionId:VersionId}' \
      --output json 2>/dev/null || echo "null")
    [[ "\${batch}" == "null" || "\${batch}" == "[]" || -z "\${batch}" ]] && break

    tmpfile=\$(mktemp)
    printf '%s' "\${batch}" | python3 -c "
import json, sys
objs = json.load(sys.stdin)
if objs: print(json.dumps({'Objects': objs}))
" > "\${tmpfile}"
    [[ -s "\${tmpfile}" ]] && \
      aws s3api delete-objects --bucket "\${bucket}" --delete "file://\${tmpfile}" >/dev/null && \
      echo "[INFO]   Deleted delete-marker batch"
    rm -f "\${tmpfile}"
  done

  # Catch any remaining non-versioned objects
  aws s3 rm "s3://\${bucket}" --recursive >/dev/null 2>&1 || true
  echo "[INFO] Bucket emptied: \${bucket}"
}

########################################
# 1. CLOUDFORMATION STACKSET
########################################

echo "════════════════════════════════════════"
echo " [1/7] CloudFormation StackSet"
echo "════════════════════════════════════════"

if aws cloudformation describe-stack-set \
    --stack-set-name "\${STACKSET_NAME}" \
    --call-as SELF >/dev/null 2>&1; then

  INSTANCE_COUNT=\$(aws cloudformation list-stack-instances \
    --stack-set-name "\${STACKSET_NAME}" \
    --query 'length(Summaries)' \
    --output text 2>/dev/null || echo "0")

  if [[ "\${INSTANCE_COUNT}" -gt "0" ]]; then
    echo "[INFO] Removing \${INSTANCE_COUNT} StackSet instance(s) from OUs..."

    # Build JSON array of OU IDs
    OU_JSON=\$(printf '"%s",' "\${OU_IDS[@]}" | sed 's/,\$//')

    OPERATION_ID=\$(aws cloudformation delete-stack-instances \
      --stack-set-name "\${STACKSET_NAME}" \
      --deployment-targets "OrganizationalUnitIds=[\${OU_JSON}]" \
      --regions "${AWS_REGION}" \
      --no-retain-stacks \
      --query 'OperationId' \
      --output text)

    echo "[INFO] Waiting for instance removal (operation: \${OPERATION_ID})..."
    while true; do
      STATUS=\$(aws cloudformation describe-stack-set-operation \
        --stack-set-name "\${STACKSET_NAME}" \
        --operation-id "\${OPERATION_ID}" \
        --query 'StackSetOperation.Status' \
        --output text)
      case "\${STATUS}" in
        SUCCEEDED)
          echo "[INFO] StackSet instances removed"; break ;;
        FAILED|STOPPED)
          echo "[WARN] Operation ended with status \${STATUS} — continuing"; break ;;
        *)
          echo "[INFO]   Status: \${STATUS} — waiting 15s..."
          sleep 15 ;;
      esac
    done
  else
    echo "[INFO] No StackSet instances found"
  fi

  echo "[INFO] Deleting StackSet: \${STACKSET_NAME}"
  aws cloudformation delete-stack-set \
    --stack-set-name "\${STACKSET_NAME}" \
    --call-as SELF >/dev/null
  echo "[INFO] StackSet deleted"
else
  echo "[INFO] StackSet not found: \${STACKSET_NAME}"
fi

########################################
# 2. IAM ROLE
########################################

echo "════════════════════════════════════════"
echo " [2/7] IAM Role"
echo "════════════════════════════════════════"

if aws iam get-role --role-name "\${ROLE_NAME}" >/dev/null 2>&1; then

  echo "[INFO] Detaching managed policies from role"
  while IFS= read -r arn; do
    [[ -z "\${arn}" ]] && continue
    echo "[INFO]   Detaching: \${arn}"
    aws iam detach-role-policy \
      --role-name "\${ROLE_NAME}" \
      --policy-arn "\${arn}" >/dev/null
  done < <(aws iam list-attached-role-policies \
    --role-name "\${ROLE_NAME}" \
    --query 'AttachedPolicies[].PolicyArn' \
    --output text | tr '\t' '\n')

  echo "[INFO] Deleting inline policies from role"
  while IFS= read -r name; do
    [[ -z "\${name}" ]] && continue
    echo "[INFO]   Deleting: \${name}"
    aws iam delete-role-policy \
      --role-name "\${ROLE_NAME}" \
      --policy-name "\${name}" >/dev/null
  done < <(aws iam list-role-policies \
    --role-name "\${ROLE_NAME}" \
    --query 'PolicyNames[]' \
    --output text | tr '\t' '\n')

  echo "[INFO] Deleting role: \${ROLE_NAME}"
  aws iam delete-role --role-name "\${ROLE_NAME}" >/dev/null
  echo "[INFO] Role deleted"
else
  echo "[INFO] Role not found: \${ROLE_NAME}"
fi

########################################
# 3. IAM POLICY
########################################

echo "════════════════════════════════════════"
echo " [3/7] IAM Policy"
echo "════════════════════════════════════════"

POLICY_ARN="arn:\${PARTITION}:iam::\${ACCOUNT_ID}:policy/\${POLICY_NAME}"

if aws iam get-policy --policy-arn "\${POLICY_ARN}" >/dev/null 2>&1; then

  echo "[INFO] Detaching policy from all roles"
  while IFS= read -r role; do
    [[ -z "\${role}" ]] && continue
    echo "[INFO]   Detaching from: \${role}"
    aws iam detach-role-policy \
      --role-name "\${role}" \
      --policy-arn "\${POLICY_ARN}" >/dev/null 2>&1 || true
  done < <(aws iam list-entities-for-policy \
    --policy-arn "\${POLICY_ARN}" \
    --query 'PolicyRoles[].RoleName' \
    --output text 2>/dev/null | tr '\t' '\n')

  echo "[INFO] Deleting non-default policy versions"
  while IFS= read -r vid; do
    [[ -z "\${vid}" ]] && continue
    aws iam delete-policy-version \
      --policy-arn "\${POLICY_ARN}" \
      --version-id "\${vid}" >/dev/null
  done < <(aws iam list-policy-versions \
    --policy-arn "\${POLICY_ARN}" \
    --query 'Versions[?!IsDefaultVersion].VersionId' \
    --output text 2>/dev/null | tr '\t' '\n')

  echo "[INFO] Deleting policy: \${POLICY_NAME}"
  aws iam delete-policy --policy-arn "\${POLICY_ARN}" >/dev/null
  echo "[INFO] Policy deleted"
else
  echo "[INFO] Policy not found: \${POLICY_NAME}"
fi

########################################
# 4. S3 STATE BUCKET
########################################

echo "════════════════════════════════════════"
echo " [4/7] S3 State Bucket"
echo "════════════════════════════════════════"

if aws s3api head-bucket --bucket "\${TF_STATE_BUCKET}" >/dev/null 2>&1; then
  empty_versioned_bucket "\${TF_STATE_BUCKET}"
  echo "[INFO] Deleting bucket: \${TF_STATE_BUCKET}"
  aws s3api delete-bucket --bucket "\${TF_STATE_BUCKET}" >/dev/null
  echo "[INFO] State bucket deleted"
else
  echo "[INFO] Bucket not found: \${TF_STATE_BUCKET}"
fi

########################################
# 5. S3 LOGS BUCKET
########################################

echo "════════════════════════════════════════"
echo " [5/7] S3 Logs Bucket"
echo "════════════════════════════════════════"

if aws s3api head-bucket --bucket "\${TF_LOGS_BUCKET}" >/dev/null 2>&1; then
  empty_versioned_bucket "\${TF_LOGS_BUCKET}"
  echo "[INFO] Deleting bucket: \${TF_LOGS_BUCKET}"
  aws s3api delete-bucket --bucket "\${TF_LOGS_BUCKET}" >/dev/null
  echo "[INFO] Logs bucket deleted"
else
  echo "[INFO] Bucket not found: \${TF_LOGS_BUCKET}"
fi

########################################
# 6. KMS KEY
########################################

echo "════════════════════════════════════════"
echo " [6/7] KMS Key + Alias"
echo "════════════════════════════════════════"

KMS_KEY_ID=\$(aws kms list-aliases \
  --query "Aliases[?AliasName=='\${KMS_ALIAS}'].TargetKeyId | [0]" \
  --output text 2>/dev/null || echo "None")

if [[ "\${KMS_KEY_ID}" != "None" && -n "\${KMS_KEY_ID}" ]]; then
  echo "[INFO] Deleting KMS alias: \${KMS_ALIAS}"
  aws kms delete-alias --alias-name "\${KMS_ALIAS}" >/dev/null

  echo "[INFO] Scheduling KMS key deletion (7-day window): \${KMS_KEY_ID}"
  aws kms schedule-key-deletion \
    --key-id "\${KMS_KEY_ID}" \
    --pending-window-in-days 7 >/dev/null
  echo "[INFO] KMS key scheduled for deletion"
else
  echo "[INFO] KMS key not found for alias: \${KMS_ALIAS}"
fi

########################################
# 7. OIDC PROVIDER
########################################

echo "════════════════════════════════════════"
echo " [7/7] GitHub Actions OIDC Provider"
echo "════════════════════════════════════════"

OIDC_HOST="token.actions.githubusercontent.com"
OIDC_ARN="arn:\${PARTITION}:iam::\${ACCOUNT_ID}:oidc-provider/\${OIDC_HOST}"

if aws iam get-open-id-connect-provider \
    --open-id-connect-provider-arn "\${OIDC_ARN}" >/dev/null 2>&1; then
  echo "[INFO] Deleting OIDC provider"
  aws iam delete-open-id-connect-provider \
    --open-id-connect-provider-arn "\${OIDC_ARN}" >/dev/null
  echo "[INFO] OIDC provider deleted"
else
  echo "[INFO] OIDC provider not found"
fi

########################################
# DONE
########################################

echo ""
echo "════════════════════════════════════════"
echo "✅ Teardown complete: ${TFVARS_BASENAME}"
echo "════════════════════════════════════════"
echo ""
echo "  Note: KMS key is pending deletion (7-day cancellation window)."
echo "  To cancel: aws kms cancel-key-deletion --key-id \${KMS_KEY_ID}"
echo ""
EOF

chmod +x "$OUTPUT_FILE"

echo "✅ Delete script generated: $OUTPUT_FILE"
echo ""
echo "⚠️  Upload to CloudShell and run:"
echo "   bash $(basename "$OUTPUT_FILE")"
echo ""
